import {utiles, utilesForm, utilesimge} from './request'
export const acsService = p => utiles('api/wbArticle/getPhotoUrl', p) // 图片获取
export const reqPwdLogin = p => utiles('auth/login', p) // 登录验证
export const loginVerifyToken = p => utiles('auth/loginVerifyToken', p) // oa跳转登录验证
export const getUserInfo = p => utiles('api/user/getUserInformation', p) // 获取用户信息
export const getArticleList = p => utiles('api/wbArticle/getArticleList', p) // 获取帖子列表
export const giveAlike = p => utiles('api/wbArticle/giveAlike', p) // 帖子点赞
export const deleteArticle = p => utiles('api/wbArticle/deleteArticle', p) // 帖子删除
export const addArticleReply = p => utiles('api/wbArticle/addArticleReply', p) // 帖子评论：一级二级三级
export const getReplyList = p => utiles('api/wbArticle/getReplyList', p) // 获取当前评论的帖子评论
export const getUserList = p => utiles('api/user/getUserList', p) // @人列表
export const addArticle = p => utilesForm('api/wbArticle/addArticle', p) // 发送帖子
export const addvideo = (p, func) => utilesimge('api/wbArticle/uploadArticleVideo', p, 'POST', func) // 发送视频
export const uploadHeadPhoto = p => utilesForm('api/user/uploadHeadPhoto', p) // 上传头像
export const updateUserPersonal = p => utiles('api/user/updateUserPersonal', p) // 修改个人信息
export const getUnreadNoticeList = p => utiles('api/notice/getUnreadNoticeList', p) // 获取@我的通知状态
export const getUnreadReplyList = p => utiles('api/notice/getUnreadReplyList', p) // 获取未读评论列表
export const getUnreadLikeList = p => utiles('api/notice/getUnreadLikeList', p) // 获取未读赞列表
export const addAttentionUser = p => utiles('api/attention/addAttentionUser', p) // 添加关注
export const deleteAttentionUser = p => utiles('api/attention/deleteAttentionUser', p) // 取消关注
export const addCollectArticle = p => utiles('api/attention/addCollectArticle', p) // 收藏帖子
export const complainArticle = p => utiles('api/attention/complainArticle', p) // 举报帖子
export const updateReplyStatus = p => utiles('api/notice/updateReplyStatus', p) // 修改评论状态
export const getLeftTopicsList = p => utiles('api/wbArticle/getLeftTopicsList', p) // 获取左侧热门话题列表
export const getHotArticleList = p => utiles('api/wbArticle/getHotArticleList', p) // 获取左侧热门帖子
export const getWbArticleDetails = p => utiles('api/wbArticle/getWbArticleDetails', p) // 获取帖子详情
export const addAttentionTopic = p => utiles('api/attention/addAttentionTopic', p) // 关注关注热门话题
export const getAttentionTopicList = p => utiles('api/attention/getAttentionTopicList', p) // 获取关注的话题列表
export const getAllTopicList = p => utiles('api/wbArticle/getAllTopicList', p) // 获取全部话题列表(关注/未关注)
export const updateNoticeStatus = p => utiles('api/notice/updateNoticeStatus', p) // 修改@通知状态
export const updateLikeStatus = p => utiles('api/notice/updateLikeStatus', p) // 修改赞的状态
export const getAttentionList = p => utiles('api/attention/getAttentionList', p) // 获取我关注的用户列表
export const getMyFuns = p => utiles('api/attention/getMyFuns', p) // 获取粉丝列表
export const getMyJoinArticles = p => utiles('api/wbArticle/getMyJoinArticles', p) // 我参与的（收藏，点赞，举报，转发，评论）
export const getCollectList = p => utiles('api/attention/getCollectList', p) // 获取收藏帖子列表
export const getAnnouncementList = p => utiles('/back/getAnnouncementList', p) // 获取公告列表
export const searchInfo = p => utiles('api/wbArticle/searchInfo', p) // 首页搜索人和帖子
export const searchManInfo = p => utiles('api/wbArticle/searchManInfo', p) // 首页搜索人员
export const getBannerList = p => utiles('/back/getBannerList', p) // banner列表
export const getNicknameFlag = p => utiles('api/user/getNicknameFlag', p) // 昵称重复
export const updateAnnounceStatus = p => utiles('back/updateAnnounceStatus', p) // 公告已读未读状态更改
export const deleteReply = p => utiles('api/wbArticle/deleteReply', p) // 删除评论
export const addLoginRecord = p => utiles('api/user/addLoginRecord', p) // 添加登录记录-后台导出excel
export const addQuestion = p => utilesForm('api/qa/addQuestion', p) // 发布问题
export const getMyQa = p => utiles('api/qa/getMyQa', p) // 问答左侧个人问答数量
export const getQuestionList = p => utiles('api/qa/getQuestionList', p) // 问题列表，已解决，未解决
export const complainQuestion = p => utiles('api/qa/complainQuestion', p) // 举报问题
export const getTopList = p => utiles('api/qa/getTopList', p) // 问答-排行榜
export const getNewAnswerList = p => utiles('api/qa/getNewAnswerList', p) //  问答-问题列表，最新回答
export const getQuestionDetails = p => utiles('api/qa/getQuestionDetails', p) //  问题详情
export const addAnswer = p => utiles('api/qa/addAnswer', p) //  回答问题
export const getAnswerList = p => utiles('api/qa/getAnswerList', p) //  问题回答列表
export const addAttenQuestion = p => utiles('api/qa/addAttenQuestion', p) //  关注问题
export const addAnswerlike = p => utiles('api/qa/addAnswerlike', p) //  问答列表点赞，取消点赞
export const addAnswerReply = p => utiles('api/qa/addAnswerReply', p) //  添加评论
export const getAnswerReplyList = p => utiles('api/qa/getAnswerReplyList', p) //  获取评论
export const uploadQaFile = p => utiles('api/qa/uploadQaFile', p) //  上传附件
export const getAttenNewAnswerList = p => utiles('api/qa/getAttenNewAnswerList', p) //  关注问题-最新回答
export const getAttenQuestionList = p => utiles('api/qa/getAttenQuestionList', p) //  关注问题-已解决，待解决
export const updateAcceptStatus = p => utiles('api/qa/updateAcceptStatus', p) //  采纳回答
export const updateMyAnswer = p => utiles('api/qa/updateMyAnswer', p) //  修改回答
export const complainAnswer = p => utiles('api/qa/complainAnswer', p) //  举报回答
export const selectBestAnswer = p => utiles('api/qa/selectBestAnswer', p) //  选择最佳答案
export const updateSolveYn = p => utiles('api/qa/updateSolveYn', p) //  更改问题解决状态
export const getDeclareList = p => utiles('api/qa/getDeclareList', p) //  公告栏列表
