export const GET_USERINFO = 'GET_USERINFO'
export const USER_IN = 'USER_IN'
export const USERLIST = 'USERLIST'
export const HOSTLIST = 'HOSTLIST'
export const TOKEN = 'TOKEN'
export const GET_USER = 'GET_USER'
export const GETMYQA = 'GETMYQA'
